### ISSUE TITLE
multi-gpu

### ISSUE THREAD

**Issue by bhralz** [Clinical-and-Translational-Imaging-Lab/brats-e1d3#3]
Hi,
thanks for your great work!
Can it use multi gpu for training?

**Comment by stalhabukhari** [comment]
Hi @bhralzz,

Sorry for the late reply, and thank you for your interest in our work.

Multi-GPU training is not included right now. But I think simply doing data-parallelism will require some brief changes in [`e1d3/train.py`](https://github.com/Clinical-and-Translational-Imaging-Lab/brats-e1d3/blob/main/e1d3/train.py).

Best,
Talha
