### ISSUE TITLE
dice

### ISSUE THREAD

**Issue by H-CODE6** [Clinical-and-Translational-Imaging-Lab/brats-e1d3#4]
Hello, how to evaluate dice after the test?

**Comment by stalhabukhari** [comment]
Hi,

Sorry for the delayed response. You can use some of the open source tools or the implementation in [metrics.py](https://github.com/Clinical-and-Translational-Imaging-Lab/brats-e1d3/blob/main/e1d3/utils/metrics.py) (which is a proxy) to compute the dice metric.

Best,
Talha

**Comment by H-CODE6** [comment]
I'm very sorry for your late reply. Can you recommend some evaluation websites to me? In addition, this metrics.py How should be used for evaluation?

**Comment by Xiuxiu21** [comment]
> 我很抱歉你迟到的回复。你们能向我推荐一些评估网站吗？此外，该 metrics.py 应如何用于评估？
请问 问题解决了吗
